# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a one-line script
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a multi-line script
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Build your project (replace with your actual build commands)
      - name: Build Project
        run: |
          # Replace with your build commands
          echo "Building the project..."
          # Example for a Node.js project:
          # npm install
          # npm run build
          # Replace with relevant build steps for your technology stack

      # Rebuild the project (optional if you need to force rebuild)
      - name: Rebuild Project
        run: |
          # Replace with rebuild commands if needed
          echo "Rebuilding the project..."
          # Example for a Node.js project:
          # npm run rebuild

      # Deploy your project (replace with your actual deployment commands)
      - name: Deploy Project
        run: |
          # Replace with your deploy commands
          echo "Deploying the project..."
          # Example for deploying to a server or cloud:
          # scp -r ./build user@server:/path/to/deploy
          # or for a specific deployment tool (e.g., AWS CLI, Heroku CLI)
          # aws s3 sync ./build s3://your-bucket-name
          # heroku deploy commands here



      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
